### ISSUE TITLE
remote upstream

### ISSUE THREAD

**Issue by kodeine** [FAUSheppy/nginx-configuration-examples#1]
hello,
so i was reading your blog and was trying to implement the multiplexing. I wanted to ask how can i set nginx upstream to remote ip:port. i tried it but nginx shows me a directory index of /etc/nginx/sites-enabled/

```
server{
    listen unix:/var/www/tlstunnel/nginx_socket_cert proxy_protocol;
    proxy_pass some.domain.com:8004;
}
```
it works fine with localip:8004 though.

**Comment by FAUSheppy** [comment]
This is likely because the remote server is only listening on specific SNIs and nginx resolves the domain-names.

For example:
host example.com => 93.184.216.34 (one of them anyway)

but if you try to query this IP directly:
http://93.184.216.34/

You get 404 - Not Found, which incidentally is the same you get when you do a stream proxy_pass.

As far as I am aware the proxy_ssl_name directive is not working with the stream module so you would have to set up a local->remote proxy in a http-server block.

With athq.de/144.76.115.232 it should work/works (ignoring the certificate) because my server is listening on it's IP as well, meaning if you have control over the remote server you cloud also just make it listen on non-specific SNI too.

**Comment by kodeine** [comment]
@FAUSheppy Thank you for your reply, i was able to make it work!.
Now question is, instead of openvpn, i'm trying to add tor relay.

```
map $ssl_preread_alpn_protocols $protocol_stream {
    default       127.0.0.1:7999;
    ~\bhttp/1.1\b 127.0.0.1:8001;
    ~\bh2\b       127.0.0.1:8001;
}
```
Any idea's what would be for tor here?

**Comment by FAUSheppy** [comment]
The short answer is: Don't. 

Firstly, Tor is defacto-insecure with anything but the tor-browser:

https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea

Secondly, if you want to connect your tor browser to a remote, you should use an official tor-bridge (which has obfuscation itself):

https://2019.www.torproject.org/docs/bridges.html.en

This is really out of scope for this configuration.
